### ISSUE TITLE
Docs: guide the user in the horizontal direction

### ISSUE THREAD

**Issue by alexander-nitsche** [b13/make#11]
Being a decision maker or a new TYPO3 developer i would require additional information in the documentation whether to choose this extension or the _Extension Builder_ to create new extensions. I would wonder if the reason for having two extensions might be that a TYPO3 extension can either have a CGI or a CLI interface, and if not, why the CLI interface of this extension has not been integrated into the Extension Builder. It should be added, that TYPO3 provides currently two ways to build extensions, the Extbase way and the _other_ way, which should be given a dedicate keyword which can be picked up also in the official documentation and so provide better search results for users who want to implement an extension in a specific way.

**Comment by ervaude** [comment]
The `make:extension` command only kickstarts an extension skeleton in its bare minimum, so that it is installable and ready to be filled with life. It does not make any assumptions whether or not you are going to use extbase for anything. It creates the basic files needed for any extension and does not choose a "way" for you to do things.

This could be spelled out more clearly in the Readme, I agree. So let's do tat :)

**Comment by alexander-nitsche** [comment]
Ok. But in this case, the Extension Builder can also create only an extension skeleton without any controller. So there must be still a difference that should be pointed out.

**Comment by o-ba** [comment]
Hi, I agree. We could add some sentence about the different use cases. Do you want to create a PR with a proposal?

**Comment by alexander-nitsche** [comment]
I do not know the use case of `EXT:make` exactly compared to `EXT:extension_builder`. The reasons for setting up EXT:make besides EXT:extension_builder are hopefully stored somewhere in b13's brains :)

**Comment by ervaude** [comment]
IMO, the main use case of EXT:make is to have CLI commands for boilerplating things.

**Comment by o-ba** [comment]
> IMO, the main use case of EXT:make is to have CLI commands for boilerplating things.

Exactly. While `extension_builder` comes with a backend module and a GUI, `make` is a CLI tool for those boilerplate things. This is already mentioned in the README. I therefore close this issue for now.

In case you have some other use cases / differences, which should be mentioned, please don't hesitate to create a PR for it directly.
