### ISSUE TITLE
Docs: frontend controller

### ISSUE THREAD

**Issue by alexander-nitsche** [b13/make#12]
Is there a reason why there is an explicit CLI command `make:backendcontroller` but no `make:frontendcontroller`? I would add an explanation close to the list of commands, as this question pops up immediately when reading the documentation.

**Comment by o-ba** [comment]
There is no reason. I just added a first set of commands, which I thought would be useful. What do you consider a "frontendcontroller"?

**Comment by alexander-nitsche** [comment]
Coming from the Extbase world i would consider "frontendcontroller" the handler of actions in the frontend which is used in a frontend plugin, in contrary to the "backendcontroller" which is used in a backend module.

**Comment by o-ba** [comment]
When talking about extbase, isn't this what the extension builder is for? I assume there are a lot more things to configure, compared to the backend controller since we usually rely on TSFE. Could you have a look at the necessary steps, which we would need to implement for such command?

**Comment by alexander-nitsche** [comment]
> When talking about extbase, isn't this what the extension builder is for?

Yes, just wanted to explain my understanding of terms "backend controller" and "frontend controller".

> Could you have a look at the necessary steps, which we would need to implement for such command?

I would like to stick to the naming in the documentation in this issue: i have only objections regarding the naming of the cli command: i would add an explanation in the documentation, why this is explicitly creating a backend controller, and not a general controller, i.e. why is the command not named `make:controller`?

**Comment by o-ba** [comment]
I can't follow here. I think a general controller does not exist and would lead to confusion. The "backend controller" naming is correct for this component, as can be seen on the corresponding service tag, which is also called "backend.controller".

**Comment by kvonspiczak** [comment]
Hello, just chiming in here to clear up the confusion. I think @alexander-nitsche is referring to the extbase [ActionController](https://github.com/TYPO3/typo3/blob/main/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php)  

Here is some additional information regarding that topic: https://docs.typo3.org/m/typo3/book-extbasefluid/main/en-us/7-Controllers/1-Creating-Controllers-and-Actions.html

**Comment by o-ba** [comment]
Hi @kvonspiczak ,

yes you are right. @alexander-nitsche was referring to the extbase ActionController. However, this component can not yet be kickstarted using `make`. Therefore, I don't see what should be adjust in the docs, nor do I agree with changing the command name to `make:controller`, as described in my last comment form January. Therefore, I'll close this issue for now.
