### ISSUE TITLE
Docs: register for intercept to increase visibility

### ISSUE THREAD

**Issue by alexander-nitsche** [b13/make#13]
Consider to [register](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingDocForExtension/Migrate.html) this extension documentation for rendering and publishing at docs.typo3.org to be found in its new global search.

**Comment by o-ba** [comment]
I added the configuration and a webhook. Rendering needs to be approved first.

**Comment by o-ba** [comment]
Rendering was done: https://docs.typo3.org/p/b13/make/main/en-us/
