### ISSUE TITLE
Add links to extension page

### ISSUE THREAD

**Issue by brotkrueml** [b13/make#14]
The extension page on https://extensions.typo3.org/extension/make only shows a download button. To give possible users more information please add the following links:
- Link to documentation: https://github.com/b13/make/blob/main/README.md
- Found an issue: https://github.com/b13/make/issues
- Code insights: https://github.com/b13/make
- Packagist.org: https://packagist.org/packages/b13/make

**Comment by bmack** [comment]
Added all necessary parts. seems like TER does not pick up the Packagist.org link. let's see if this is solved with the next release.

**Comment by o-ba** [comment]
Hi, all information are now available on the detail page.
