### ISSUE TITLE
Create Classes folder when configuring namespace

### ISSUE THREAD

**Issue by susannemoog** [b13/make#15]
If you do

make:extension

and then try to run extension:setup it will fail because the classes folder does not exist (but is configured in the composer.json file). The command should not create a "broken" setup, instead I would suggest to create the "Classes" folder when make:extension is called.

**Comment by o-ba** [comment]
Hi @susannemoog, I checked this and can confirm there is an error regarding the missing `Classes/` directory. However it seems to be triggered by Symfony and ist not related to the composer.json. Anyways, I agree the directory should be create in any case, since it's referenced at multiple places.
