### ISSUE TITLE
syntax error, unexpected '::'

### ISSUE THREAD

**Issue by Starraider** [b13/make#6]
After installation of b13/make the TYPO3 CLI is broken. 
The following error appears:
```bash
Uncaught TYPO3 Exception syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting '('
thrown in file /var/www/html/var/cache/code/di/DependencyInjectionContainer_51630ad3884f230bb20352380033e634d449c8af.php
in line 3233
```
If I open this file it shows the following function:
```php
   /**
     * Gets the public 'B13\Make\Command\Component\CommandCommand' shared autowired service.
     *
     * @return \B13\Make\Command\Component\CommandCommand
     */
    protected function getCommandCommandService::class)
    {
        $this->services['B13\\Make\\Command\\Component\\CommandCommand'] = $instance = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstanceForDi(\B13\Make\Command\Component\CommandCommand::class);

        $instance->setName('make:command');
        $instance->setDescription('Create a \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstanceForDi(command');

        return $instance;
    }
```
As you can see, the function name is broken.

I used a fresh DDEV installation of TYPO3 v10.4.22 with PHP v7.4.26.
After deinstallation of b13/make the TYPO3 CLI works again fine.

**Comment by o-ba** [comment]
Hi, thanks for your report. It seems like this is a TYPO3 Core bug, see https://forge.typo3.org/issues/95607. Unfortunately this was only fixed in master (v12 and v11) but not backported to v10. Will check if we can backport the Core patch, otherwise we will change the commands' description.

**Comment by o-ba** [comment]
I fixed the commands' description since it's not foreseeable when a v10 release will happen. Thanks again for reporting.

**Comment by Starraider** [comment]
Yes, now it works fine! 
Thank you for the quick fix!
